### PR TITLE
Project 3: query multiple tables.

### PR DESCRIPTION
**Pull request by binhussen**
## Project 3: query multiple tables.
In this PR I have implemented:-
- Altered Table's `primary key` and `foreign key` for joining tables.
- Modified animals Table to connect with other Table within `foreign keys`.
- Queried queries that answered questions by using `JOIN`.

### CODE REVIEW

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @binhussen ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly take a screenshot of the results of your queries and add the screenshot with the results of your queries to your Pull Request description. :+1: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by binhussen** [comment]
Thanks, @mahbubul14 for your feedback, I forget to do so, but I will do it now.

**Comment by binhussen** [comment]
## Project 3: query multiple tables.
In this PR I have implemented:-
- Altered Table's `primary key` and `foreign key` for joining tables.
- Modified animals Table to connect with other Table within `foreign keys`.
- Queried queries that answered questions by using `JOIN`.

### Some go Queries Result
j1

j2

j3

j4

j5

j6

**Review by addod19 — APPROVED** [review]
### Hi @binhussen, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Nice job adding the query screenshots to our PR :100: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by binhussen** [comment]
Thanks, @addod19 for your feedback and for approving my code.

**Pull request merged**
